[project]
name = "gc-extension"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mat73",
    "matplotlib",
    "numba==0.61.2",
    "numpy==2.2.0",
    "pandas",
    "scikit-learn",
    "statsmodels",
    "torch==2.2.2",
    "tqdm",
]

[dependency-groups]
dev = [
    "pylint",
    "pytest",
]

[tool.uv]
package = false
